# Nama Workflow
name: Build OpenNDS on ImmortalWrt x86_64

# Pemicu Workflow
on:
  # Izinkan pemicu manual dari tab Actions di GitHub
  workflow_dispatch:
  # Pemicu otomatis setiap kali ada push ke branch 'main'
  push:
    branches:
      - main

# Variabel Lingkungan
env:
  # Target repositori ImmortalWrt dan versinya
  IMMORTALWRT_REPO: https://github.com/immortalwrt/immortalwrt.git
  IMMORTALWRT_BRANCH: openwrt-24.10
  
  # File konfigurasi kustom
  CONFIG_FILE: .config
  
  # Pesan commit untuk rilis
  RELEASE_MESSAGE: "Rilis Build OpenNDS Terbaru"

# Pekerjaan (Jobs) yang akan dijalankan
jobs:
  build:
    # Menggunakan runner terbaru dari GitHub (Ubuntu)
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout kode dari repositori Anda
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Langkah 2: Instal dependensi yang diperlukan untuk proses build
      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses5-dev libssl-dev python3-setuptools rsync \
            unzip zlib1g-dev file wget

      # Langkah 3: Kloning source code ImmortalWrt
      - name: Clone ImmortalWrt Source Code
        run: |
          git clone --depth 1 -b $IMMORTALWRT_BRANCH $IMMORTALWRT_REPO immortalwrt
          cd immortalwrt

      # Langkah 4: Perbarui dan instalasi feeds (koleksi paket)
      - name: Update and Install Feeds
        run: |
          cd immortalwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      # Langkah 5: Buat file konfigurasi (.config) kustom
      - name: Generate Custom Configuration
        run: |
          cd immortalwrt
          # Hapus .config jika sudah ada untuk memastikan konfigurasi bersih
          rm -f $CONFIG_FILE
          
          # Menyiapkan konfigurasi dasar untuk target x86_64
          cat <<EOF > $CONFIG_FILE
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_generic=y

          # Pilih library libmicrohttpd tanpa SSL
          CONFIG_PACKAGE_libmicrohttpd-no-ssl=y
          # Pastikan versi SSL tidak terpilih
          # CONFIG_PACKAGE_libmicrohttpd is not set
          
          # Pilih paket OpenNDS
          CONFIG_PACKAGE_opennds=y
          EOF
          
          # Terapkan konfigurasi default dan kustom
          make defconfig

      # Langkah 6: Kompilasi firmware/paket
      # Hanya build paket OpenNDS dan dependensinya (-j$(nproc))
      - name: Compile The Firmware
        run: |
          cd immortalwrt
          make package/opennds/compile V=s -j$(nproc)

      # Langkah 7: Siapkan artifak untuk diunggah
      - name: Prepare Artifacts
        run: |
          mkdir -p artifacts
          # Cari file .ipk dari OpenNDS dan dependensinya, lalu salin ke folder artifacts
          find immortalwrt/bin/packages/x86_64/base -name "*opennds*.ipk" -exec cp {} artifacts/ \;
          find immortalwrt/bin/packages/x86_64/base -name "*libmicrohttpd-no-ssl*.ipk" -exec cp {} artifacts/ \;
          
      # Langkah 8: Unggah artifak (file .ipk) hasil build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: opennds-packages-x86_64
          path: artifacts/
